# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `mocha` gem.
# Please instead update this file by running `bin/tapioca gem mocha`.

# source://mocha-1.14.0/lib/mocha/version.rb:1
module Mocha; end

# source://mocha-1.14.0/lib/mocha/backtrace_filter.rb:2
class Mocha::BacktraceFilter
  # @return [BacktraceFilter] a new instance of BacktraceFilter
  #
  # source://mocha-1.14.0/lib/mocha/backtrace_filter.rb:5
  def initialize(lib_directory = T.unsafe(nil)); end

  # source://mocha-1.14.0/lib/mocha/backtrace_filter.rb:9
  def filtered(backtrace); end
end

# source://mocha-1.14.0/lib/mocha/backtrace_filter.rb:3
Mocha::BacktraceFilter::LIB_DIRECTORY = T.let(T.unsafe(nil), String)

# source://mocha-1.14.0/lib/mocha/deprecation.rb:4
class Mocha::Deprecation
  class << self
    # Returns the value of attribute messages.
    #
    # source://mocha-1.14.0/lib/mocha/deprecation.rb:6
    def messages; end

    # Sets the attribute messages
    #
    # @param value the value to set the attribute messages to.
    #
    # source://mocha-1.14.0/lib/mocha/deprecation.rb:6
    def messages=(_arg0); end

    # Returns the value of attribute mode.
    #
    # source://mocha-1.14.0/lib/mocha/deprecation.rb:6
    def mode; end

    # Sets the attribute mode
    #
    # @param value the value to set the attribute mode to.
    #
    # source://mocha-1.14.0/lib/mocha/deprecation.rb:6
    def mode=(_arg0); end

    # source://mocha-1.14.0/lib/mocha/deprecation.rb:8
    def warning(*messages); end
  end
end

# source://mocha-1.14.0/lib/mocha/ruby_version.rb:3
Mocha::RUBY_V2_PLUS = T.let(T.unsafe(nil), TrueClass)

# source://mocha-1.14.0/lib/mocha/version.rb:2
Mocha::VERSION = T.let(T.unsafe(nil), String)
